config/routes.rb
Skorowidz::Application.routes.draw do

  resources :project_users

  get "temp/myupdate"

  get "field_histories/index"

  get "field_histories/new"

  get "field_histories/edit"

  get "field_histories/create"

  get "field_histories/show"

  resources :games

  resources :projects
  resources :users
  resources :sessions
  resources :password_resets
  resources :secret
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
   root :to => "sessions#new" 
 

  get "password_resets/new"
  get "sessions/new"
  get "users/new" 
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "recover_password" => "users#recover_password", :as =>"recover_password"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "sessions#new"

  match ':controller(/:action(/:id))(.:format)'  
    
      

   

   
end

app/models/user.rb
#!/usr/local/bin/ruby
# coding: utf-8
class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains #to jest callback
  has_many :field_histories
  has_many :projects, :through=>:field_histories
  
  has_many :project_users
  has_many :projects, :through=>:project_users
  
  before_create { generate_token(:auth_token) }
 
  attr_accessible :email, :password_hash, :password_salt, :role
  #has_secure_password
  attr_accessible :name, :password, :password_confirmation, :user_roles_id
  
  attr_accessor :password
  before_save :encrypt_password
  
  
  validates :name, :length=>{:maximum=>240}
  validates_confirmation_of :password
  validates_presence_of :password, :name, :on => :create
  validates_presence_of :email, :name
  validates_uniqueness_of :email    
  validates_format_of :email, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i, :on => :create
  validates_inclusion_of :role, :in => ["admin", "trener","biuro", "sprzedaż"]
    

  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end    
  end

    #def self.authenticate(email, password)
  def authenticate(email, password)
    user = User.find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  

def send_password_reset
  generate_token(:password_reset_token)
  self.password_reset_sent_at = Time.zone.now
  save!
  UserMailer.password_reset(self).deliver
end

def generate_token(column)
  begin
    self[column] = SecureRandom.urlsafe_base64
  end while User.exists?(column => self[column])
end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
      before_filter :require_admin_login
      
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      UserMailer.registration_confirmation(@user).deliver
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])    
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        UserMailer.recover_password(@user).deliver
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def index
    @users = User.all       
  end
  
    def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  
 def random_pass(length=8) #nie używane
    chars = [*('A'..'Z'), *('a'..'z'), *(0..9)]
    (0..length).map {chars.sample}.join
  end
  
   def show
    @user = User.find(params[:id])
    
     if @user.save
      respond_to do |format|
        format.html #show.html.erb
        format.json { render json: @user }
     end    
    end
  end

end

app/views/users/edit.html.erb
	<div class="links_top">
		<%= link_to 'Back to users', users_path %>
	</div>
<h1>Edytuj użytkownika</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :role %><br />
    <%= f.text_field :role %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
   
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/index.html.erb
	<div class="links_top">
<%= link_to 'Back to projects', projects_path %>
</div>
<h1>Spis oraz tworzenie nowych użytkowników</h1>
<table>
<tr>
	<th>Email:</th>
	<th>Rola użytkownika:</th>
	<th>Imię:</th>
	<th>Nazwisko:</th>
	</tr><% @users.each do |user| %>
  <tr>
    <td><span class="name"><%= user.email %></span></td>
    <td><span class="name"><%= user.role %></span></td>
    <td><span class="name"><%= user.name %></span></td>
    <td class="show"><%= link_to 'Edytuj użytkownika', edit_user_path(user) %></td>   
    <td class="show"><%= link_to 'Pokaż', user %></td>
    <td class="del"><%= link_to 'Usuń', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<p><%= link_to 'Create user', new_user_path %></p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :role %><br />
    <%= f.text_field :role %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<div class="links_top">
<%= link_to 'Edit', edit_user_path(@user) %> <br/>
<%= link_to 'Back', users_path %>
</div>
	<h1>Szczegóły użytkownika</h1>
<p id="notice"><%= notice %></p>
<div class="metr">
	
	<table class="tabl">
	<tr>
		<td class="head"><b>Email:</b> </td>
		<td class="ins"><%=@user.email%> </td> 
	</tr>
	
	<tr>
	  <td class="head"><b>Imie:</b></td>
	  <td class="ins"><%= @user.name %></td>
	</tr>
	
	<tr>
	  <td class="head"><b>Rola:</b></td>
	  <td class="ins"><%= @user.role %></td>
	</tr>
		
</table>