config/routes.rb
Skorowidz::Application.routes.draw do

  resources :project_users

  get "temp/myupdate"

  get "field_histories/index"

  get "field_histories/new"

  get "field_histories/edit"

  get "field_histories/create"

  get "field_histories/show"

  resources :games

  resources :projects
  resources :users
  resources :sessions
  resources :password_resets
  resources :secret
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
   root :to => "sessions#new" 
 

  get "password_resets/new"
  get "sessions/new"
  get "users/new" 
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "recover_password" => "users#recover_password", :as =>"recover_password"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "sessions#new"

  match ':controller(/:action(/:id))(.:format)'  
    
      

   

   
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skorowidz</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag 'jquery', 'application' %>
  <%= csrf_meta_tags %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> 
</head>
<body>
<div id="page">
<div id="top">
    <span id="logo">Metryczki</span>
    <div id="nav">
      <%= link_to "Projects", projects_url %>
      <%= link_to "Games", games_url %>
      <% if current_user && current_user.role.eql?('admin')%>
          <%= link_to "Manage users", users_path%>
      <%end%>
    </div>
    <div id="user_nav">
      <% if current_user %>
        <%= current_user.email %> (<%= current_user.role %>), <%= link_to "Log out", log_out_path %>
      <% end %>
    </div>
</div>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</div>
</body>
</html>